import Head from "next/head";
import CardSection from "../components/CardSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Latest from "../components/Latest";
import axios from "axios";

import styles from "../styles/Home.module.css";

export default function Home(props) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>আর্থিক</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.main}>
          <Latest posts={props.latest} />
          <CardSection posts={props.posts} />
        </main>
        <Footer />
      </div>
      <script
        data-name="BMC-Widget"
        data-cfasync="false"
        src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js"
        data-id="arthik"
        data-description="Support me on Buy me a coffee!"
        data-message=""
        data-color="#5F7FFF"
        data-position="Right"
        data-x_margin="15"
        data-y_margin="15"
      ></script>
    </>
  );
}

export async function getServerSideProps(context) {
  const response = await axios.get(
    "https://jsonplaceholder.typicode.com/posts"
  );
  const data = response.data;
  const latest = [
    data[data.length - 1],
    data[data.length - 2],
    data[data.length - 3],
  ];
  return {
    props: {
      posts: data,
      latest,
    },
  };
}
