import Head from "next/head";
import Image from "next/image";
import CardSection from "../components/CardSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Latest from "../components/Latest";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>আর্থিক</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Latest />
        <CardSection />
      </main>
      <Footer />
    </div>
  );
}
